import 'friend_model.dart';

class FriendsContext {
  List<FriendModel> friends = [
    FriendModel("Joe", "", 1),
    FriendModel("Griffin", "", 1),
    FriendModel("Ben chao", "", 1),
    FriendModel("Pierce", "", 1),
    FriendModel("Jeff", "", 1),
    FriendModel("Sean fitz", "", 1),
    FriendModel("Sharif", "", 1),
    FriendModel("Anta", "", 1),
    FriendModel("Chris chalmers", "", 1),
    FriendModel("Chives", "", 1),
    FriendModel("Tyler", "", 1),
    FriendModel("Chelsea", "", 1),
    FriendModel("Miles", "", 1),
    FriendModel("Logan", "", 1),
    FriendModel("Sean Allen", "", 1),
    FriendModel("Curty", "", 1),
    FriendModel("Trevis", "", 1),
    FriendModel("Chris lee", "", 1),
    FriendModel("Danny", "", 1),
    FriendModel("Bentley", "", 1),
    FriendModel("Tim", "", 1),
    FriendModel("Rob ", "", 1),
    FriendModel("Andy ", "", 1),
    FriendModel("Derek", "", 1),
    FriendModel("David", "", 1),
    FriendModel("Brandon", "", 1),
    FriendModel("Segalla", "", 1),
    FriendModel("Pentland", "", 1),
    FriendModel("Lemon", "", 1),
    FriendModel("Philip", "", 1),
    FriendModel("McDonough", "", 1),
    FriendModel("Zouk", "", 1),
    FriendModel("Foss", "", 1),
    FriendModel("Klu", "", 1),
    FriendModel("Joey", "", 1),
    FriendModel("Borke", "", 1),
    FriendModel("Tenno", "", 1),
    FriendModel("Graham", "", 1),
    FriendModel("Jason", "", 1),
    FriendModel("Cp", "", 1),
    FriendModel("Elliott", "", 1),
    FriendModel("Tian", "", 1),
    FriendModel("Nick rayl", "", 1),
    FriendModel("Guy", "", 1),
    FriendModel("Vansh", "", 1),
    FriendModel("Eric ", "", 1),
    FriendModel("Roy", "", 1),
    FriendModel("Jack Stulic ", "", 1),
    FriendModel("Kush", "", 1),
    FriendModel("Patwari", "", 1),
    FriendModel("Geoff", "", 1),
    FriendModel("Georgios", "", 1),
    FriendModel("Aidan", "", 1),
    FriendModel("Lynda", "", 1),
    FriendModel("Mike Hall", "", 1),
    FriendModel("Rex", "", 1),
    FriendModel("Kyle", "", 1),
    FriendModel("Alex salvatore", "", 1),
    FriendModel("Lim", "", 1),
    FriendModel("Tony", "", 1),
    FriendModel("Dughi", "", 1),
    FriendModel("NK", "", 1),
    FriendModel("Neil", "", 1),
    FriendModel("Santi", "", 1),
    FriendModel("Juliet", "", 1),
    FriendModel("Worms", "", 1),
    FriendModel("Erik", "", 1),
    FriendModel("Ofir", "", 1),
    FriendModel("Devin", "", 1),
    FriendModel("Drew", "", 1),
    FriendModel("Will youngs", "", 1),
    FriendModel("Zack pajka", "", 1),
    FriendModel("Sam Marshall", "", 1),
    FriendModel("Himanshu", "", 1),
    FriendModel("Q", "", 1),
    FriendModel("Blake", "", 1),
    FriendModel("Christine", "", 1),
    FriendModel("Irene", "", 1),
    FriendModel("Derek", "", 1),
    FriendModel("Khoa", "", 1),
    FriendModel("Christian", "", 1),
    FriendModel("Kyle", "", 1),
    FriendModel("Jacob", "", 1),
    FriendModel("Sav", "", 1),
    FriendModel("Pedro", "", 1),
    FriendModel("Clint", "", 1),
    FriendModel("Whitney", "", 1),
    FriendModel("Chris webb", "", 1),
    FriendModel("Iman", "", 1),
    FriendModel("Anand", "", 1),
    FriendModel("Chris lim", "", 1),
    FriendModel("Scott", "", 1),
    FriendModel("Sandrine", "", 1),
    FriendModel("Cotter", "", 1),
    FriendModel("Alex Ross ", "", 1),
    FriendModel("Matt Chan", "", 1),
    FriendModel("Josh", "", 1),
    FriendModel("Aaron He", "", 1),
    FriendModel("Demi ", "", 1),
    FriendModel("Danielle", "", 1),
    FriendModel("Shreyas", "", 1),
    FriendModel("Gaurang", "", 1),
    FriendModel("Dan", "", 1),
    FriendModel("Ara", "", 1),
    FriendModel("Siva", "", 1),
    FriendModel("Paul Blakely", "", 1),
    FriendModel("Rani", "", 1),
    FriendModel("Ryan Mick", "", 1),
    FriendModel("Garo", "", 1),
    FriendModel("Chris Fuller", "", 1),
    FriendModel("Rounak", "", 1),
    FriendModel("Joe Dao", "", 1),
    FriendModel("Devin Thomson", "", 1),
    FriendModel("Xiaohu", "", 1),
    FriendModel("Dimitar", "", 1),
    FriendModel("JunYoung", "", 1),
    FriendModel("Yating", "", 1),
    FriendModel("Daniel Alkalai", "", 1),
    FriendModel("Nick Saretzky", "", 1),
    FriendModel("Adil", "", 1),
    FriendModel("Kyle Bendickson", "", 1),
    FriendModel("Salina", "", 1),
    FriendModel("Sophia", "", 1),
    FriendModel("Andy Lawton", "", 1),
    FriendModel("Hemanth", "", 1),
    FriendModel("Siggi", "", 1),
    FriendModel("Thomas Yoon", "", 1),
    FriendModel("John Morse", "", 1),
    FriendModel("Doshi", "", 1),
    FriendModel("Serge", "", 1),
    FriendModel("Shaheen", "", 1),
    FriendModel("Vijay", "", 1),
    FriendModel("Andre", "", 1),
    FriendModel("Owen Thomas", "", 1),
    FriendModel("Andy Phan", "", 1),
  ];

  List<FriendModel> getAllFriends() {
    return friends;
  }

  List<FriendModel> getRandomFriends({int num = 1}) {
    if (num >= friends.length) return friends;
    return (friends.toList()..shuffle()).take(num).toList();
  }
}
